### ISSUE TITLE
Follow up on #198

### ISSUE THREAD

**Issue by ujhede** [nordicopen/easee_hass#200]
### Question

I am not sure what happens to comments on closed issues so sorry for creating a new one if it is not necessary.

 I have not charged my car for about a week since I last restarted/upgraded HA and all sensors showed up as "unavailable" the entire time. So last night I started a charge session on one of my chargers and that charger then showed values for all sensors.

The other charger (the master one) is still showing as unavailable.

Both chargers show up as online in easee.cloud

So it looks to me like there is something holding back the integration until the first charging session.

Update!  Looks like that after i logged in to easee.cloud to check the status of the chargers both chargers are now showing fine in HA after having been unavailable for more than a week.

### What version of the integration are you using?

latest

**Comment by olalid** [comment]
Well, I can not reproduce this problem on my installation.
But I can imagine that something like this could happen if the API does not return initial status when HA is started.
I.e. when HA starts, the Easee integration will first poll the API to get the complete status of the devices, then it will connect to the signalr stream to get further updates pushed when they occur.
Restarting the integration (or HA) should fix the problem, if the cloud is functioning correctly. Did you try that?
