### ISSUE TITLE
Car ID

### ISSUE THREAD

**Issue by Mkay505** [nordicopen/easee_hass#241]
### Feature request

First of all - thank you for your great integration.

Is there a way to read a kind of "Car" ID? So you would know which car is being charged at which of the two wall boxes.

### What version of the integration are you using?

newest

**Comment by astrandb** [comment]
No, the charger does not know which car is connected..

**Comment by olalid** [comment]
A workaround can be to use RFID cards, and scan different cards depending on which car you are charging.
There are some attributes on the status entity that are supposed to show which RFID card was scanned, but it is kind of untested...

**Comment by olalid** [comment]
Well, seems that user informtion I mentioned above seems to not work.

**Comment by Mkay505** [comment]
Thanks for the check.

**Comment by t112013** [comment]
i have the "same issue" two chargers and two cars. so i am guessing by starting my automations with two triggers, one for each charger that will trigger on state change from unplugged to awaiting for start (if i remember correcy) then i have guessed the charger, then i do a force update for the tesla, and wait for one min just in case and i test is the teslas charger has state connected in the last min. 
my only issue is if i connect both cars at the same car :P  
Second car is a id.buzz comming next week, i heard their api is bit slow can it can it updateded every minute.

anyone has any better idea ?

**Comment by olalid** [comment]
Closing since there is no obvious way to implement this.
