### ISSUE TITLE
Unable to check Status value in Automation

### ISSUE THREAD

**Issue by ridderr** [nordicopen/easee_hass#363]
### The problem

I would like to check the Status in an automation, but I only see the options: Unavailable & Unknown. I would expected to see: disconnected, awaiting_start, charging, ready_to_charge, completed, error.

I have solved this using an template but for readability it would be nicer to have these status values to check on.

### Version of Easee integration having the issue?

0.9.55

### Version of Home Assistant Core having the issue?

Home Assistant 2023.10.3

### Additional information

![Schermafbeelding 2023-10-16 112848](https://github.com/fondberg/easee_hass/assets/12719238/d79cdea7-43c7-4689-906a-c6cdefbd4d14)

**Comment by olalid** [comment]
You can type "disconnected" etc in that field, you do not have to select something from the drop-down.

Not sure if it is possible to populate the drop-down with other values, it would look nicer of course...

**Comment by astrandb** [comment]
This is not a bug, it is a missing feature. The concept in Home Assistant that handles these menus is called Device Automations. We put it on the ToDo-list.

**Comment by Mats1717** [comment]
Hi am sorry but a cant see this working now. Think it worked 6 months ago when a set up some notification automations completed, disconnected and charging. Trying to add a notification for error but the list is still as above. Running 0.9.55
Regards Mats

**Comment by astrandb** [comment]
@Mats1717 
> Hi am sorry but a cant see this working now. Think it worked 6 months ago when a set up some notification automations completed, disconnected and charging. Trying to add a notification for error but the list is still as above. Running 0.9.55 Regards Mats

You can type the state in the select box. 
There is a new feature that is not released yes (#364). You will then be able to create a trigger on the **_device_** level with full GUI support. Note that triggers on the **_status entity_** will still have to be entered as text.
