### ISSUE TITLE
Authorization from integration

### ISSUE THREAD

**Issue by joffaHA** [nordicopen/easee_hass#376]
### Feature request

Hi, I spoke with Easee support a few days ago regarding authorization from the API. Acording to Easee this should be possible with the API. 
As of now the only way for a user to authorize a session is by tapping an RFID/NFC-tag, or by opening the Easee-app.
Based on your knowledge, is it possible to do so with this repo?

### What version of the integration are you using?

 v0.9.55

**Comment by olalid** [comment]
In theory the start/stop commands (which are available as services) should do just that.
See https://developer.easee.com/docs/settings
I have never personally tried it though, I have no need for that function in my installation.

**Comment by gaga191281** [comment]
Hi.. this is definitely a must have feature. Works like a charm on my ioBroker. 
Please add this, otherwise this integration is more or less useless to me.

**Comment by astrandb** [comment]
Please test the start and stop services as @olalid suggested. 
Goto Developer tools->Services and select the service Easee EV Charger: Action command, select your target device and then select Start.

That should authorize the charger in the same way an RFID tag does. 
If it works as you expect we can consider to add a button entity to simplify the use of the service action.

**Comment by HolgerMiara** [comment]
Hi @gaga191281 and @joffaHA, 
This is maybe off-topic, as it doesn't relate to the integration. But why don't you authenticate with a random RFID card right away when plugging the car in? (like your Visa or the access card of your workplace) You are physically standing there anyhow and the cable will be locked afterwards. 
At least that's what I am doing to separately log charge sessions of our private car and the company car. (I am logging the sessions in the Easee cloud though; the HA integration seems agnostic about which user has authenticated.)

**Comment by zinen** [comment]
Does this also work if I have a charge plan setup on the Eease? I mean just reading the command called "start" in the home assistant I'm not thinking that this really means either "start now (override charge plan)" or "start when allowed by charge plan". Could some help be added to the command text clearifying this?

**Comment by zinen** [comment]
I read your link and agree that the naming is purly stolen from the API doc. But then again the API doc also writes this in details below stating what the start/stop aactually do. This piece of the detail is missing inside home assistant
