### ISSUE TITLE
EVCC does not start

### ISSUE THREAD

**Issue by MichaelS1955** [nordicopen/easee_hass#378]
### The problem

Hi,
evcc does not find the config file. But the config file is in the right place. Since installation I did not change the file.
![image](https://github.com/nordicopen/easee_hass/assets/118118054/6d56e394-0f5a-4160-a3a0-ce3dd78ff1cd)

What is wrong?

Thank you

### Version of Easee integration having the issue?

Current version: 0.122.1

### Version of Home Assistant Core having the issue?

2923.11.2

**Comment by olalid** [comment]
Probably this is the right project?
https://github.com/evcc-io/evcc/tree/master

**Comment by MichaelS1955** [comment]
you are right, sorry

**Comment by olalid** [comment]
No worries.
