### ISSUE TITLE
Read and pass RFID ID to Home Assistant?

### ISSUE THREAD

**Issue by rogerrem** [nordicopen/easee_hass#385]
### Feature request

We have 5 chargers and I was thinking that I would like to get the RFID identificator when someone taps their card for charging into HA.
The chargers are "Public/Open" during daytime (Deactivated at nighttime), and we have a screen where we can see what each charger is doing.
The feature I would like to set up is that even though its Public/Open, people would tap their card to send their ID to HA so I can use that ID to match to the name of the person charging and show this on the screen along with charging speed etc. 

Does the API open up for passing the RFID information at all?

:)

-R-

### What version of the integration are you using?

0.9.56

**Comment by olalid** [comment]
Closing since this can not be implemented.
