### ISSUE TITLE
Set dynamic charger limit don’t work, missing Device ID

### ISSUE THREAD

**Issue by karllinder** [nordicopen/easee_hass#393]
### The problem

Hi

When calling set_charger_dymanic_limit from a developer tool, it’s requesting Device Id. Dropdown is empty and input manual charger ID (serial number of Easee device) it’s say:
This service requires field device_id, please enter a valid value for device_id
All other part of the integration is working.

Core 
2024.2.3
Supervisor
2024.02.0
Operating System
11.5
Frontend
20240207.1

### Version of Easee integration having the issue?

0.9.57

### Version of Home Assistant Core having the issue?

2024.2.3

### Anything in the logs that might be useful for us?

```txt
No issues found i logs.
```

**Comment by astrandb** [comment]
There are three differen ways to specify the target unit. Please see here:
https://github.com/nordicopen/easee_hass?tab=readme-ov-file#use

**Comment by karllinder** [comment]
Thanks, that was the solution.
