### ISSUE TITLE
Log Failture

### ISSUE THREAD

**Issue by andybali** [nordicopen/easee_hass#403]
### The problem

Log Failture

### Version of Easee integration having the issue?

0.9.58

### Version of Home Assistant Core having the issue?

2024.3.3

### Anything in the logs that might be useful for us?

```txt
`Logger: homeassistant.helpers.translation
Quelle: helpers/translation.py:345
Erstmals aufgetreten: 07:18:24 (2 Vorkommnisse)
Zuletzt protokolliert: 07:18:24

Validation of translation placeholders for localized (de) string component.easee.device_automation.condition_type.error_pen_fault failed
Validation of translation placeholders for localized (de) string component.easee.device_automation.trigger_type.error_pen_fault failed`
```

**Comment by astrandb** [comment]
This is just a warning message that the German translation is incomplete.
Fixed in Lokalise. Will be included in next release of the integration.
