### ISSUE TITLE
Version 0.9.59

### ISSUE THREAD

**Issue by Mats1717** [nordicopen/easee_hass#422]
### The problem

This is not a big issue but with newest version some automations need some attention.

Before it was
- service: easee.set_circuit_dynamic_limit
    data:
      currentP1: 16
      currentP2: 16
      currentP3: 16

Now it bust be
  - service: easee.set_circuit_dynamic_limit
    data:
      current_p1: 16
      current_p2: 16
      current_p3: 16
Regards Mats

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.5.3

**Comment by olalid** [comment]
That is intentional, it is changed because it was necessary to get better translation support. See also the release notes.

**Comment by Mats1717** [comment]
No problem i fixed mine already it was more of an heads up for everyone. Missed it I realease note.
