### ISSUE TITLE
Online entities stay on 'connected' even though wallbox has no power

### ISSUE THREAD

**Issue by cschlipf** [nordicopen/easee_hass#430]
### The problem

1. Switch off the fuse for the wallbox. 
2. Wait until wallbox shows as offline in Easee app
3. Check status of <wallboxname>_online -> It's still marked as connected

Waited for half an hour.

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.6.1

**Comment by olalid** [comment]
The timeout before a unit is marked as offline should be 17 minutes.

Can you see a line saying "SignalR stream connected" in the log (if not, the integration was in polling mode which may break a lot of things since it is not as well tested).

**Comment by cschlipf** [comment]
```
2024-06-10 08:42:02.633 INFO (MainThread) [pysignalr.transport] State change: connecting -> connected
2024-06-10 08:42:02.633 DEBUG (MainThread) [pyeasee.easee] SignalR stream connected
2024-06-10 08:42:02.633 DEBUG (MainThread) [pyeasee.easee] Subscribing to EHXXXXXX
2024-06-10 08:42:02.639 DEBUG (MainThread) [pyeasee.easee] Subscribing to EHXXXXXX
```

I will try again and wait longer than for 30 minutes. It already takes pretty long for the app to notice that the boxes are offline. If the 17 minutes come on top, that could have been the issue.

**Comment by cschlipf** [comment]
Tested again and waited longer. And after 33 minutes it happened :-)

So I was too impatient. Sorry for taking your time. It works as expected and thank you very much for your work.

**Comment by olalid** [comment]
Still a bit strange that it took that long. 17 minutes should be from when the device lost power, the time it takes in the app is unrelated to the integration.
I will have a look at it at some point to make sure there is not bug lurking here...

**Comment by cschlipf** [comment]
Thank you. Feel free to open this issue if you feel it would help you.
