### ISSUE TITLE
Get Equalizer amp limit as configurable

### ISSUE THREAD

**Issue by nickderg** [nordicopen/easee_hass#448]
### Feature request

Is it possible to make the Equalizer amp limit as a configurable value in HA? 
It would be easier to let HA control the amp depending on an automation or scheme.

### What version of the integration are you using?

0.9.59

**Comment by olalid** [comment]
You can use the dynamic circuit limit instead, it has the same effect. Lowest limit on a given phase always "wins" over other limits.
There is no known way to control the equalizer limit in any case, it happens outside of the public API.

**Comment by olalid** [comment]
Closing since there is no known way to implement the requested feature.
