### ISSUE TITLE
I volunteer for French translation

### ISSUE THREAD

**Issue by alepee** [nordicopen/easee_hass#449]
### Feature request

Linked to https://github.com/nordicopen/easee_hass/issues/374

---

If you create a French locale on Lokalise, I can do my part and translate it into French 😄

While creating this issue, I want to take the opportunity to thank you and all the contributors for this integration with Home Assistant 👏 🎉

### What version of the integration are you using?

0.9.59

**Comment by astrandb** [comment]
@alepee Thank you. French (fr) is now open for translation.

**Comment by alepee** [comment]
And I think I'm done :) I needed to search a few things within the codebase to better understand the context.

Just to be sure, "Idle current" refer to 

	1.	Courant de repos : The current that flows in a circuit when it is powered on but not supplying any active load. It is often the minimum current required to keep a device operational, ready to respond to a demand.
	2.	Courant à vide : The current consumed by a device or circuit when it operates without any connected load. It is the current drawn in the absence of an active energy demand.

Despite this one it should be ok

**Comment by astrandb** [comment]
That was fast!
The term "enable idle current" is used by Easee to ensure that the car can get up to 6A for heating/cooling even when it it not charging. It is only relevant if there are more than one charger in a circuit. In the swedish translation we have used "Viloström" which is translated literally to "Resting current".

The french translation will be included in next release of the integration.

**Comment by alepee** [comment]
Ok, so "Courant de repos" seems to fit best :)
