### ISSUE TITLE
Ease core model not recognized

### ISSUE THREAD

**Issue by Exstor** [nordicopen/easee_hass#451]
### The problem

Using version 0.9.59 got a new Easee Charge Core installed today as replacement for my Easee Home.
It was recognised and seams to work, but the model is not recognized. In the Device listing the model says "productCode: 102".

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.5.3

### Additional information

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/d597006a-45a1-41b2-8c06-203f0b5998e9">

**Comment by olalid** [comment]
Thanks, we did not know the product code until now, will be fixed when we make next release.

**Comment by olalid** [comment]
See https://github.com/nordicopen/easee_hass/pull/453

**Comment by olalid** [comment]
This issue is most likely solved in v0.9.60. Please update and test.
