### ISSUE TITLE
Dynamic circuit limit, Max circuit limit, Offline circuit limit UNKNOWN

### ISSUE THREAD

**Issue by jacoscar** [nordicopen/easee_hass#454]
### The problem

Dynamic circuit limit, Max circuit limit, Offline circuit limit are shown as unknown and don't appear in the history graph

However I can successfully set dynamic circuit limit when the vehicle is charging (confirmed in the Easee App), it's just not shown as an entity or in the history graph
![image](https://github.com/user-attachments/assets/d73e911c-65a1-48f1-845e-680130d60282)

![image](https://github.com/user-attachments/assets/40181b9c-0db8-48d7-b6e6-7819b6a68ad7)
![image](https://github.com/user-attachments/assets/026b6a51-324c-4d7c-b69f-9efb75205a18)

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.9.0

**Comment by olalid** [comment]
This issue is most likely solved in v0.9.60. Please update and test.

**Comment by jacoscar** [comment]
tested and ok
