### ISSUE TITLE
Disable/enable weekly schedule

### ISSUE THREAD

**Issue by Andurilll** [nordicopen/easee_hass#461]
### Feature request

I would like to request the addition of a feature that allows users to activate & deactivate the charging schedule.
The state is currently read by binary_sensor.p6_wochentlicher_zeitplan, 

The idea is to provide the ability to control the charge schedule (like activating or deactivating scheduled charging) within Home Assistant, similar to how the schedule charge status is currently being monitored with the binary_sensor.p6_wochentlicher_zeitplan. This would greatly improve automation flexibility, especially for users who need to override or manually control charging based on dynamic conditions like energy prices or solar power availability.

Possible API Reference:
It seems that this might be achievable via the [API](https://developer.easee.com/reference/post_api-chargers-chargerid-charge-schedule-features), but I am not entirely sure if this is the correct endpoint.

Also could it be a feature called "Force Charging". This would allow temporary disabling the "schedule charge" functionality and enable after one charge (or time frame).

### What version of the integration are you using?

easee-0.9.59

**Comment by olalid** [comment]
There are already services to control schedule. Not sure if you missed that or if you are asking to extend them in some way?

**Comment by Andurilll** [comment]
Maybe i missed it? I can't find a option to enable/disable the schedule charging. Where is it? Or how can i trigger?

**Comment by olalid** [comment]
Yes, maybe that is an oversight that it cannot be disabled...?
Enable you can do for sure with the easee.set_basic_charge_plan and easee.set_weekly_charge_plan services.

**Comment by olalid** [comment]
You can use easee.action_command with option delete_basic_charge_plan or delete_weekly_charge_plan to disable them.

**Comment by Andurilll** [comment]
does this delete the charge plan entirely? would i have to build it again?

**Comment by olalid** [comment]
Override schedule service calls this API: https://developer.easee.com/reference/post_api-chargers-chargerid-commands-override-schedule

The delete services calls these APIs:
https://developer.easee.com/reference/delete_api-chargers-chargerid-basic-charge-plan
https://developer.easee.com/reference/delete_api-chargers-chargerid-weekly-charge-plan

And the set services calls these APIs:
https://developer.easee.com/reference/post_api-chargers-chargerid-basic-charge-plan
https://developer.easee.com/reference/post_api-chargers-chargerid-weekly-charge-plan

**Comment by Andurilll** [comment]
Seems what i suggested is not what's possible now. In the App there is a slider to on/off the schedule without deleting it.

**Comment by olalid** [comment]
I do not think the delete function does more than disable it really, but the issue would be that we do not have a function to enable it again without actually specifying a new schedule at the same time.
So yes, there is room for improvement, I will put it on my mental list of things to look into...

**Comment by olalid** [comment]
Work in progress still, but included here: https://github.com/nordicopen/easee_hass/pull/483

**Comment by olalid** [comment]
Released now, please let us know if your problem was solved.

**Comment by Andurilll** [comment]
> Released now, please let us know if your problem was solved.

Works perfekt from Automation Editor. Thanks a lot! 👍🏻💪🏻
