### ISSUE TITLE
Unable to turn on or off charger

### ISSUE THREAD

**Issue by StefanFeenstra** [nordicopen/easee_hass#465]
### The problem

I’m unable to turn on or off my charger. When I toggle the switch it’s changing back to the original value in a couple of seconds

### Version of Easee integration having the issue?

0.9.59

### Version of Home Assistant Core having the issue?

2024.9.0

**Comment by aifiks** [comment]
It's most probably due to issues with Easee Cloud API. You probably also cannot change the dynamic charging limit. See [#463 ]

https://status.easee.com/

**Comment by StefanFeenstra** [comment]
Thanks found link also. And also tried the easee developer portal with api tester and indeed same problem.
