### ISSUE TITLE
Phase mode adjustment

### ISSUE THREAD

**Issue by retetiba** [nordicopen/easee_hass#479]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

Can someone help. Using this integration happily, but have one issue. I have 2 cars, one needs 3 phase charging the other 1 phase charging. Issue is that the car using one phase charging can not handle automatic / 3 phase charging mode. In the app solved by changing manually to 1 phase. 

However I saw this option can be set via the easee API. I thought I was quite handy but unable to add this in HA. 

Sample code: 
curl --request POST \
     --url https://api.easee.com/api/chargers/EHYYYYY/commands/set_phase_mode \
     --header 'Authorization: Bearer  XXXXXX' \
     --header 'content-type: application/*+json' \
     --data '{"phaseMode":1}'
Is it possible to add this option to the new version? Or perhaps help me out how to use this in HA automation action. 

As thank you, I  support I started already helping in translation support :-)

Thank you for the excellent work, looking at all comments, this integration is used a lot!

### Version of Easee integration having the issue?

0.9.61

### Version of Home Assistant Core having the issue?

2024.10

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by olalid** [comment]
It is not possible right now to change this setting from the integration.
You can however force 1-phase mode by setting the dynamic circuit current limit to 0 on 2 of the phases.
Or the dynamic charger limit, but that is not persistent over time, so not as easy to use.

**Comment by retetiba** [comment]
Hi,

I know. Therefor my request to built in. The workaround does not work for me. One of the cars does not start charging when put on 3 phase mode unfortunately.

I am trying to find out how to do this my self via the curl command or hopefully you can help me with this.

Thanks for the reply and thinking!

Regards

Rene


Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Ola Lidholm ***@***.***>
Verzonden: Sunday, October 6, 2024 7:29:22 PM
Aan: nordicopen/easee_hass ***@***.***>
CC: retetiba ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nordicopen/easee_hass] Phase mode adjustment (Issue #479)


It is not possible right now to change this setting from the integration.
You can however force 1-phase mode by setting the dynamic circuit current limit to 0 on 2 of the phases.
Or the dynamic charger limit, but that is not persistent over time, so not as easy to use.

**Comment by olalid** [comment]
I have started working on implementing a new service for this, it should make it in to a future version soon.

**Comment by retetiba** [comment]
You are the best!
Thank you !!
________________________________
Van: Ola Lidholm ***@***.***>
Verzonden: Sunday, October 6, 2024 11:45:51 PM
Aan: nordicopen/easee_hass ***@***.***>
CC: retetiba ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nordicopen/easee_hass] Phase mode adjustment (Issue #479)


I have started working on implementing a new service for this, it should make it in to a future version soon.

**Comment by olalid** [comment]
Work in progress still, but included here: https://github.com/nordicopen/easee_hass/pull/483

**Comment by retetiba** [comment]
Hi Ola,

Thank you!

Can I already test such an update (how do I update my integration?) or should I wait.

Looking forward to this option

Regards

Rene


Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Ola Lidholm ***@***.***>
Verzonden: Thursday, October 10, 2024 8:13:48 PM
Aan: nordicopen/easee_hass ***@***.***>
CC: retetiba ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nordicopen/easee_hass] Phase mode adjustment (Issue #479)


Work in progress still, but included here: #483<https://github.com/nordicopen/easee_hass/pull/483>

**Comment by olalid** [comment]
You can certainly test if you want. The current master is what we intend to release unless we find some issues. We will likely release it tomorrow.

The general thing you need to do to manually update is to download from git and copy the files in the in the repository custom_components/easee folder to your <config>/custom_components/easee. Then restart HA.

**Comment by olalid** [comment]
Released now, please let us know if your problem was solved.

**Comment by retetiba** [comment]
Hi Ola,

I will do, this week on holiday, will try soon.

Thanks for the great support!

Regards Rene
________________________________
Van: Ola Lidholm ***@***.***>
Verzonden: Wednesday, October 16, 2024 2:26:44 PM
Aan: nordicopen/easee_hass ***@***.***>
CC: retetiba ***@***.***>; Author ***@***.***>
Onderwerp: Re: [nordicopen/easee_hass] Phase mode adjustment (Issue #479)


Released now, please let us know if your problem was solved.

**Comment by enoch85** [comment]
On the subject, I want to control the phases through NODE-RED. So when the price is low, let this kick in:

![image](https://github.com/user-attachments/assets/c447c4fc-a595-4cab-a96f-ce4c7d492ec9)

Or do I need to actually create a template for it and call that instead?

**Comment by olalid** [comment]
I do not know anything about node red, but looks reasonable to me to do it that way.

**Comment by enoch85** [comment]
Figured it out:

![image](https://github.com/user-attachments/assets/bd3a664e-9157-489d-8a9d-1d28bb3127fe)

The secret: ``{"device_id":"XXXX-REPLACEME-XXXX","phase_mode":"1_phase"}

**Comment by olalid** [comment]
There has "always" been a sensor for that, the charger status sensor has an attribute Config phaseMode.
The values is however a bit cryptic, 2 means auto, 1 means 1 phase and 3 means 3 phase.

**Comment by enoch85** [comment]
Thanks for the pointer! 

JFTR in case anyone else comes here searching. This checks if the phase is 1 or not, and outputs the current phase.

![image](https://github.com/user-attachments/assets/b1c17c62-3eb2-465b-b991-10faeda37315)

**Comment by enoch85** [comment]
Anyway, I can confirm it's working, so feel free to close.
