### ISSUE TITLE
Schedule management on Easee One

### ISSUE THREAD

**Issue by jacoscar** [nordicopen/easee_hass#492]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

I have enabled a weekly schedule on my Easee One (1 phase UK version).

I can see an entity called "binary_sensor.easee_one_weekly_schedule" which seems to reflect that. However I cannot find a way to turn this on or off in Home Assistant.
There is a switch called "switch.easee_one_smart_charging" but it doesn't do anything for me: what is it supposed to do?
This is what the schedule section in my app look like

![IMG_7850](https://github.com/user-attachments/assets/8b68f717-c99d-404e-9b1e-079bc2288ec7)

### Version of Easee integration having the issue?

0.9060

### Version of Home Assistant Core having the issue?

2024.8.3

**Comment by olalid** [comment]
Check out the services that the integration provides. easee.action_command has some commands to turn schedules on and off for instance.

**Comment by olalid** [comment]
The smart charging switch only changes the light color of the LEDs on the charger btw.

**Comment by jacoscar** [comment]
Actually, there isn't anything to turn on or off the schedule. There are options to create new schedules (day by day or a single instance), but there is no actual switch to turn it on or off (or at lease I cannot find it).
The action_command does not have a turn on/off schedule
![image](https://github.com/user-attachments/assets/f78266c7-2c38-41bf-a527-0380857bc988)

**Comment by olalid** [comment]
Update to lastest version and you will be some functions to enable/disable schedules. They were introduces in v0.9.62.

That being said, I like the idea of having a switch, I will look in to changing the binary schedule sensors into switches in some future version.

**Comment by olalid** [comment]
See https://github.com/nordicopen/easee_hass/pull/501 for future implementation of switch.
