### ISSUE TITLE
inconsistent naming of new action "set_load_balancing"

### ISSUE THREAD

**Issue by HolgerMiara** [nordicopen/easee_hass#494]
### Feature request

Hi, 
I find the naming of the new action `set_load_balancing` confusing, as the associated sensor is called `binary_sensor.XXXXXXXX_surplus_charging` and its attributes also make reference to `Surplus charging`. Also the app is using the term "Surplus energy". 

From the app, I would rather associate the opposite mode "Monitoring the fuse load" with the term `load_balancing`. 

I don't want to be pedantic and it is not a problem if you know it; but it might be confusing for the novel user at first sight. Wouldn't it hence make sense to change the name of the action to `set_surplus_charging`?

### What version of the integration are you using?

0.9.62

### Anything in the logs that might be useful for us?

```txt
n/a
```

### Additional information

n/a

**Comment by olalid** [comment]
Yes, that is a fair point, the naming is a bit confusing, I will look in to changing it in some future release.

I guess in my mind these things are one and the same really, surplus charging is really just change of the settings of the load balancing.

**Comment by HolgerMiara** [comment]
Thanks! 
It was just a friendly remark, trust you understood it as such. I will keep an eye on your future releases and look forward to the implementation.  
However, no rush; I am not waiting impatiently ;-)

**Comment by olalid** [comment]
This PR will change the service name to set_surplus_charging.
The binary sensor will also change to switch for easier manual control.
https://github.com/nordicopen/easee_hass/pull/501
