### ISSUE TITLE
Validation of translation placeholders error

### ISSUE THREAD

**Issue by ridderr** [nordicopen/easee_hass#506]
### Before creating an issue...

- [x] There is no open issue describing the same problem
- [x] I am running latest versions of the integration and of Home Assistant
- [x] I have checked the operational status of the Easee API

### The problem

I'm having this error/warning in the logfile
`Validation of translation placeholders for localized (nl) string component.easee.issues.numeric_deprecation.title failed: ({''} != {'argument'})`

### Version of Easee integration having the issue?

V0.9.64

### Version of Home Assistant Core having the issue?

2024.11.1

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.helpers.translation
Bron: helpers/translation.py:285
Eerst voorgekomen: 15:08:44 (1 gebeurtenissen)
Laatst gelogd: 15:08:44

Validation of translation placeholders for localized (nl) string component.easee.issues.numeric_deprecation.title failed: ({''} != {'argument'})
```

**Comment by astrandb** [comment]
Thank you for reporting. Fixed and will be included in next release.
