### ISSUE TITLE
french translation correction

### ISSUE THREAD

**Issue by rvb89** [nordicopen/easee_hass#524]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

Hello,

I noticed some errors in the french translation.
Energy par Heure =>Energie par Heure
The word courant written a couple of times: courrant

If needed I could edit it on Lokalise.

Thanks

### Version of Easee integration having the issue?

0.9.65

### Version of Home Assistant Core having the issue?

2024.11.3

**Comment by astrandb** [comment]
Thank you for the report. Please make the corrections in Lokalise and they will be included in next release of the integration.

**Comment by rvb89** [comment]
Thanks for the reply.
I tried to edit it in Lokalise but I don't have the French showing, only English, Dutch, German, Icelandic, Norwegian, Romanian, Swedish.
Did I miss something ?

**Comment by astrandb** [comment]
Now you should see French.

**Comment by rvb89** [comment]
I just checked and found the translations were right in the file, after searching the issue is coming from the charger card.
Btw, I added some of the missing translations in french.

**Comment by olalid** [comment]
Thanks, contributions to translations are appreciated.
