### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by dali99** [nordicopen/easee_hass#543]
### Feature request

Hello!

I was packaging this project for a repository and noticed it does not include a license file. Because of this, I had to mark it as unfree. If this isn't intentional, it would be great if you could select and add a license to the project.

Typically, the process involves getting consensus from all contributors and ensuring they agree to license their contributions under the chosen license.

Adding a license is a good idea in general, as the project currently exists in a bit of a legal gray area. Without a license, no one technically has the right to distribute or modify the code - even the creators - since using third-party contributions without explicit permission could be considered copyright infringement.

Thanks in advance!

### What version of the integration are you using?

easee-0.9.67

**Comment by astrandb** [comment]
Thank you for the reminder. We have now assigned MIT license.
