### ISSUE TITLE
Cable locked permanently entity class

### ISSUE THREAD

**Issue by vibrog** [nordicopen/easee_hass#86]
The "Cable permanently locked charger" device seems to be implemented as a switch, not a lock.
When included in Lovelace it appears as a switch, not LOCK/UNLOCK.

![Screenshot 2020-11-29 at 12 03 59](https://user-images.githubusercontent.com/67639/100540047-0c8da200-323b-11eb-8c59-84df5106f09a.png)

**Comment by astrandb** [comment]
Yes, it is intentional. We will look at pros and cons of changing representation for a future release.
